docker run --rm -it --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" --gpus all nvidia/cuda:11.0-base bash

FROM nvidia/cuda:11.0-base

WORKDIR /home

apt-get update

apt-get install x11-apps

apt-get install -y curl wget

 wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

chmod 700 Miniconda3-latest-Linux-x86_64.sh

./Miniconda3-latest-Linux-x86_64.sh

eval "$(/root/miniconda3/bin/conda shell.bash hook)"

conda init

apt-get install -y libglu1-mesa-dev libgl1-mesa-dev libosmesa6-dev xvfb ffmpeg curl patchelf libglfw3 libglfw3-dev cmake zlib1g zlib1g-dev swig

pip install gym

apt-get install vim -y

 conda install matplotlib

conda install -y tensorflow-gpu
